ATTACK_RULES = {
    "XSS": [
        r"javascript:",
        r"<script",
        r"</script",
        r"alert\s*\(",
        r"confirm\s*\(",
        r"prompt\s*\(",
        r"onerror\s*=",
        r"onload\s*=",
        r"onclick\s*=",
        r"<img",
        r"<svg",
        r"<iframe",
        r"document\.cookie",
        r"eval\s*\(",
        r"innerhtml",
    ],

    "SQLi": [
        r"union\s+select",
        r"or\s+1=1",
        r"and\s+1=1",
        r"drop\s+table",
        r"insert\s+into",
        r"delete\s+from",
        r"update\s+.*set",
        r"sleep\s*\(",
        r"benchmark\s*\(",
        r"information_schema",
        r"xp_cmdshell",
        r"--",
        r"#",
    ],

    "Command Injection": [
        r"cmd=",
        r"exec\s*\(",
        r"system\s*\(",
        r"shell_exec",
        r"passthru",
        r"powershell",
        r"whoami",
        r"wget\s+",
        r"curl\s+",
        r"nc\s+",
        r"netcat",
        r";\s*ls",
        r";\s*cat",
        r"&&",
        r"\|\|",
    ],

    "Path Traversal": [
        r"\.\./",
        r"\.\.\\",
        r"etc/passwd",
        r"boot\.ini",
        r"windows/win\.ini",
        r"proc/self/environ",
    ],

    "File Inclusion": [
        r"file://",
        r"php://",
        r"data://",
        r"expect://",
        r"input://",
        r"include=",
        r"require=",
    ],

    "SSRF": [
        r"169\.254\.169\.254",
        r"127\.0\.0\.1",
        r"localhost",
        r"0\.0\.0\.0",
        r"metadata\.google",
        r"metadata\.internal",
        r"file://",
    ],

    "Sensitive File Access": [
        r"\.env",
        r"config\.py",
        r"settings\.py",
        r"id_rsa",
        r"id_dsa",
        r"\.git",
        r"\.svn",
        r"wp-config\.php",
    ],

    "Scanner / Recon": [
        r"nikto",
        r"sqlmap",
        r"acunetix",
        r"nessus",
        r"nmap",
        r"dirbuster",
        r"gobuster",
        r"wpscan",
        r"burpsuite",
    ],

    "Malicious Upload": [
        r"\.php",
        r"\.jsp",
        r"\.aspx",
        r"\.exe",
        r"\.sh",
        r"\.bat",
        r"\.cmd",
        r"multipart/form-data",
    ],

    "Open Redirect": [
        r"redirect=",
        r"next=http",
        r"url=http",
        r"return=http",
        r"continue=http",
    ],
}